export const SET_REPOS = 'REPOS_ACTION:SET_REPOS';
export const SET_TOTAL_REPOS = 'REPOS_ACTION:SET_TOTAL_REPOS';
export const SET_IS_LOADING = 'REPOS_ACTION:SET_IS_LOADING';
export const TO_DEFAULT = 'REPOS_ACTION:TO_DEFAULT';
